baseurl = "https://cml-new.netlify.com/"
languageCode = "en-us"
title = "Carmanuls Lib"
author = "Carmanuls Lib"
copyright = "&copy; 2016. All rights reserved."
contentDir = "content"
layoutDir = "layouts"
publishDir = "public"
paginate = 10

[indexes]
  tag = "tags"
  topic = "topics"
  make = "makes"

[permalinks]
  manual = "/:section/:title/"
[params]
  # Shown in the home page
  subtitle = "German Car Manuals"
  brand = "Carmanuls Lib"
  googleAnalytics = "Your Google Analytics tracking ID"
  disqus = "Your Disqus shortname"
  # CSS name for highlight.js
  highlightjs = "androidstudio"
  dateFormat = "02 Jan 2006, 15:04"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 2
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 3
    identifier = "about"
    url = "/about/"
  [[menu.main]]
    name = "Contact"
    pre = "<i class='fa fa-phone fa-fw'></i>"
    weight = 4
    url = "/contact/"

[social]
  twitter = "*"
  facebook = "*"
  instagram = "*"
  github = "yoshiharuyamashita"
  stackoverflow = "*"
  linkedin = "*"
